export const orders = [
  {
    id: "#ORD-82937",
    customer: {
      name: "Alice Brown",
      email: "alice.brown@example.com",
      phone: "+1 (555) 777-8888",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    date: "2023-05-15",
    address: "456 Elm St, Anytown, CA 91234",
    products: [
      { name: "Wireless Mouse", price: 24.99, quantity: 2 },
      { name: "Keyboard Wrist Rest", price: 15.5, quantity: 1 },
    ],
    total: 65.48,
    status: "Processing",
    paymentMethod: "Credit Card",
    paymentStatus: "Paid",
    trackingNumber: "1Z999AA1234567890",
    notes: "Customer requested expedited shipping.",
    supportTickets: [],
  },
  {
    id: "#ORD-91826",
    customer: {
      name: "Charlie Davis",
      email: "charlie.davis@example.com",
      phone: "+1 (555) 222-3333",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    date: "2023-05-14",
    address: "789 Oak Ave, Somecity, NY 54321",
    products: [{ name: "Bluetooth Speaker", price: 89.99, quantity: 1 }],
    total: 89.99,
    status: "Shipped",
    paymentMethod: "PayPal",
    paymentStatus: "Paid",
    trackingNumber: "927489274982",
    notes: null,
    supportTickets: [
      {
        subject: "Inquiry about shipping date",
        status: "Open",
        lastUpdate: "2023-05-14 14:23",
      },
    ],
  },
  {
    id: "#ORD-12345",
    customer: {
      name: "Bob Johnson",
      email: "bob.johnson@example.com",
      phone: "+1 (555) 123-4567",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    date: "2023-05-13",
    address: "123 Main St, Anytown, CA 91234",
    products: [
      { name: "Wireless Earbuds", price: 129.99, quantity: 1 },
      { name: "Phone Case", price: 19.99, quantity: 1 },
    ],
    total: 149.98,
    status: "Delivered",
    paymentMethod: "Credit Card",
    paymentStatus: "Paid",
    trackingNumber: "1Z000AAA0000000000",
    notes: null,
    supportTickets: [],
  },
  {
    id: "#ORD-67890",
    customer: {
      name: "Eve Williams",
      email: "eve.williams@example.com",
      phone: "+1 (555) 987-6543",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    date: "2023-05-12",
    address: "456 Oak Ave, Anytown, CA 91234",
    products: [{ name: "Smart Watch", price: 199.99, quantity: 1 }],
    total: 199.99,
    status: "Cancelled",
    paymentMethod: "PayPal",
    paymentStatus: "Refunded",
    trackingNumber: null,
    notes: "Customer cancelled order due to late delivery.",
    supportTickets: [],
  },
  {
    id: "#ORD-24680",
    customer: {
      name: "John Smith",
      email: "john.smith@example.com",
      phone: "+1 (555) 555-5555",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    date: "2023-05-11",
    address: "789 Pine Ln, Anytown, CA 91234",
    products: [{ name: "Laptop Sleeve", price: 29.99, quantity: 1 }],
    total: 29.99,
    status: "Pending",
    paymentMethod: "Credit Card",
    paymentStatus: "Pending",
    trackingNumber: null,
    notes: null,
    supportTickets: [],
  },
]
